= Review of bipolar transistor operation

'''
[#2018-01-10]
2018-01-10 class time content.

'''

Bipolar transistors are named as such because both _electrons_ and _holes_ participate in the device's operation.




== Structure

Figure <<bjt-planar>> shows the side view of an _npn_ BJT as it would be fabricated on a chip.


[#bjt-planar]
.Cross section of a planar BJT
image:NPN_BJT_(Planar)_Cross-section.svg[]
// from: https://en.wikipedia.org/wiki/File:NPN_BJT_(Planar)_Cross-section.svg

[#bjt-current-flow]
.Bipolar current flow in active mode
image:NPN_BJT_Basic_Operation_(Active).svg[]
// from: https://en.wikipedia.org/wiki/File:NPN_BJT_Basic_Operation_(Active).svg



NOTE: This is a note


TIP: This is a tip


IMPORTANT: This is important.


CAUTION: This is a caution.


WARNING: This is a warning.





https://en.wikipedia.org/wiki/Bipolar_junction_transistor




[#bjt-large-signal-model]
image::bjt-large-signal-model.svg[foo,100%]



== Useful tables


.Bipolar transistor modes
[cols="1,1,1,7"]
|===
|B-E junction |B-C junction |Mode |Equations

|Reverse
|Reverse
|cutoff
|latexmath:[
\begin{cases}
i_C \approx 0 \\
i_B \approx 0
\end{cases}
]

|Forward
|Forward
|saturation
|latexmath:[
\begin{cases}
V_{BE} \approx 0.6 V \\
V_{CE} = V_{CE sat} \approx 0.2 V \\
i_C \rightarrow \text{set by circuit conditions} \\
i_B \rightarrow \text{must be } > I_C/\beta
\end{cases}
]

|Forward
|Reverse
|active
|latexmath:[
\begin{cases}
V_{BE} \approx 0.6 V \\
V_{CE} \rightarrow \text{set by circuit conditions} \\
i_C = \begin{cases}
        \alpha \, i_E \\
        \beta \, i_B \\
        I_S \exp \left( v_{BE} / V_T \right)
      \end{cases} \\
i_B = i_C / \beta \\
\end{cases}
]

|Reverse
|Forward
|rev-active
|(your transistor is in backwards)

|===



.Transistor parameter definitions
[cols=".^1,.^3,.^5"]
|===
| Term | Name | Definition

|latexmath:[\beta]
|common-emitter current gain
|latexmath:[\dfrac{i_C}{i_B} = \dfrac{\beta}{1 + \beta}]

|latexmath:[\alpha]
|common-base current gain
|latexmath:[\dfrac{i_C}{i_E} = \dfrac{\alpha}{1 - \alpha}]

|latexmath:[V_T]
|thermal voltage
|latexmath:[\dfrac{k_B T}{q}]

|===


