= Bipolar transistor operation

:sect: &#167;

'''
[#2018-01-10]

Bipolar transistors are named as such because both _electrons_ and _holes_ participate in the device's operation.


== Useful tables

NOTE: This section is at the top of the page for quick reference.


.Bipolar transistor modes
[cols="1,1,1,7"]
|===
|B-E junction |B-C junction |Mode |Equations

|Reverse
|Reverse
|cutoff
|latexmath:[
\begin{cases}
i_C \approx 0 \\
i_B \approx 0
\end{cases}
]

|Forward
|Forward
|saturation
|latexmath:[
\begin{cases}
V_{BE} \approx 0.6 V \\
V_{CE} = V_{CE sat} \approx 0.2 V \\
i_C \rightarrow \text{set by circuit conditions} \\
i_B \rightarrow \text{must be } > I_C/\beta
\end{cases}
]

|Forward
|Reverse
|active
|latexmath:[
\begin{cases}
V_{BE} \approx 0.6 V \\
V_{CE} \rightarrow \text{set by circuit conditions} \\
i_C = \begin{cases}
        \alpha \, i_E \\
        \beta \, i_B \\
        I_S \exp \left( v_{BE} / V_T \right)
      \end{cases} \\
i_B = i_C / \beta \\
\end{cases}
]

|Reverse
|Forward
|rev-active
|(your transistor is in backwards)

|===




'''




.Transistor parameter definitions
[cols=".^1,.^3,.^5"]
|===
| Term | Name | Definition

|latexmath:[\beta]
|common-emitter current gain
|latexmath:[\dfrac{i_C}{i_B} = \dfrac{\beta}{1 + \beta}]

|latexmath:[\alpha]
|common-base current gain
|latexmath:[\dfrac{i_C}{i_E} = \dfrac{\alpha}{1 - \alpha}]

|latexmath:[V_T]
|thermal voltage
|latexmath:[\dfrac{k_B T}{q}]

|===



== Structure and Physics

Figure <<bjt-planar>> shows the side view of an _npn_ BJT as it would be fabricated on a chip.
The _order_ of the three-layer sandwich determines the *type* (_npn_ or _pnp_), while the _doping level_ of the outer layers determines the **C**ollector and **E**mitter terminal labels.


[#bjt-planar]
.Cross section of a planar BJT
image:NPN_BJT_(Planar)_Cross-section.svg[]
// from: https://en.wikipedia.org/wiki/File:NPN_BJT_(Planar)_Cross-section.svg
// modified emitter to add "+" to doping

[#bjt-current-flow]
.Bipolar current flow in active mode
image:NPN_BJT_Basic_Operation_(Active).svg[]
// from: https://en.wikipedia.org/wiki/File:NPN_BJT_Basic_Operation_(Active).svg



NOTE: This is a note


TIP: This is a tip


IMPORTANT: This is important.


CAUTION: This is a caution.


WARNING: This is a warning.





.Where can I read more?
****
* The Wikipedia page https://en.wikipedia.org/wiki/Bipolar_junction_transistor[Bipolar junction transistor]

****



== Circuit Analysis

=== Ebers-Moll


=== Shortcuts

There is a section at the end of most chapters in <<cmosvlsi>> called "`Pitfalls and Fallacies`" that give some hints on where it is easy to over- or under-think an issue.
A favorite in this context is:

{sect} foo bar

[quote, '<<cmosvlsi>> section 2.6, page 93']
____
*Using excessively complicated models for manual calculations*

Because models cannot be perfectly accurate, there is little value in using excessively complicated models, particularly for hand calculations.
Simpler models give more insight on key trade-offs and more rapid feedback during design.
____

==== Example analysis

image:ce-basic.svg[]



[#bjt-large-signal-model]
image::bjt-large-signal-model.svg[]





[bibliography]
== References

- [[[cmosvlsi, CMOS VLSI]]] CMOS VLSI Design - A Circuit and Systems Perspective
