= Bipolar transistor operation

ifeval::["{docname}" != "guidebook"]
include::subs.adoc[]
endif::[]

'''
[#2018-01-10]

Bipolar transistors are named as such because both _electrons_ and _holes_ participate in the device's operation.


== Useful tables

NOTE: These tables are at the top for quick reference.


[#bjt-modes]
.Bipolar transistor modes
[cols=".^1,.^1,.^1,.^7"]
|===
|B-E junction |B-C junction |Mode |Equations

|Reverse
|Reverse
|cutoff
|latexmath:[
\begin{cases}
i_C \approx 0 \\
i_B \approx 0
\end{cases}
]

|Forward
|Forward
|saturation
|latexmath:[
\begin{cases}
V_{BE} \approx 0.6 V \\
V_{CE} = V_{CE sat} \approx 0.1 \text{ to } 0.2 V \\
i_C \rightarrow \text{set by circuit conditions} \\
i_B \rightarrow \text{must be } > I_C/\beta
\end{cases}
]

|Forward
|Reverse
|active
|latexmath:[
\begin{cases}
V_{BE} \approx 0.6 V \\
V_{CE} \rightarrow \text{set by circuit conditions} \\
i_C = \begin{cases}
        \alpha \, i_E \text{, or } \approx i_E\\
        \beta \, i_B \\
        I_S \exp \left( v_{BE} / V_T \right)
      \end{cases} \\
i_B = i_C / \beta \text{, or } \approx 0\\
\end{cases}
]

|Reverse
|Forward
|rev-active
|(your transistor is in backwards)

|===




'''



[#bjt-parameters]
.Transistor parameter definitions
[cols=".^1,.^3,.^5"]
|===
| Term | Name | Definition

|latexmath:[\beta]
|common-emitter current gain
|latexmath:[\beta = \dfrac{i_C}{i_B}]

|latexmath:[\alpha]
|common-base current gain
|latexmath:[\alpha = \dfrac{i_C}{i_E}]

|
|relationships
|latexmath:[\beta = \dfrac{\alpha}{1 - \alpha}\\
\alpha = \dfrac{\beta}{\beta + 1}]

|latexmath:[V_T]
|thermal voltage
|latexmath:[\dfrac{k_B T}{q} \approx 26\,\mathrm{mV} \text{ at } 300\,\mathrm{K} \text{(room temp)}]

|latexmath:[V_A]
|Early voltage
|&approx; 100V for discrete or 20V on IC

|latexmath:[\beta]
|for hand analysis
|&approx; 100 for discrete or 20 on IC

|===

NOTE: <<AoE>> only mentions *Early voltage* and refers you to "`Chapter 2x`" of a (future) supplemental book.
See https://en.wikipedia.org/wiki/Early_effect[Wikipedia: Early effect] for a good description of this phenomenon.




== *pn* junction diode review


[latexmath]
++++
v_C(t) = \left( V_{\mathrm{final}} - V_{\mathrm{initial}} \right) \left[1 -
\exp\left(\frac{-t}{\tau}\right)\right] + V_{\mathrm{initial}}
++++

A little algebra yields an alternate equation:

[latexmath]
++++
v_C(t) = V_{\mathrm{final}} + (V_{\mathrm{initial}} - V_{\mathrm{final}})\exp\left(\dfrac{-t}{RC}\right)
++++


[#gandalf-diode]
.Diode
image::gandalf-diode.svg[Gandalf diode,width=300]


== Structure and Physics

Figure <<bjt-planar>> shows the side view of an _npn_ BJT as it would be fabricated on a chip.
The _order_ of the three-layer sandwich determines the *type* (_npn_ or _pnp_), while the _doping level_ of the outer layers determines the **C**ollector and **E**mitter terminal labels.


[#bjt-planar]
.Cross section of a planar BJT
image::NPN_BJT_(Planar)_Cross-section.svg[]
// from: https://en.wikipedia.org/wiki/File:NPN_BJT_(Planar)_Cross-section.svg
// modified emitter to add "+" to doping

[#bjt-current-flow]
.Bipolar current flow in active mode
image::NPN_BJT_Basic_Operation_(Active).svg[]
// from: https://en.wikipedia.org/wiki/File:NPN_BJT_Basic_Operation_(Active).svg



NOTE: This is a note


TIP: This is a tip


IMPORTANT: This is important.


CAUTION: This is a caution.


WARNING: This is a warning.





.Where can I read more?
****
* The Wikipedia page https://en.wikipedia.org/wiki/Bipolar_junction_transistor[Bipolar junction transistor]

****



== Circuit Models

=== Ebers-Moll model

The Ebers-Moll model is accurate, useful, and therefore well-known.
It accounts for normal _pn_ junction current flow and the "`transistor action`" current flow due to the shared middle region.


.Ebers-Moll model for NPN
image::Ebers-Moll_model_schematic_(NPN).svg[Ebers-Moll, 400]
// from: https://en.wikipedia.org/wiki/File:Ebers-Moll_model_schematic_(NPN).svg

The diode currents for Figure <<_Ebers-Moll_model_for_NPN>> are found in the normal way by their voltages:

[latexmath]
++++
\begin{align}
I_{ED} &= I_{SE} \left[ \exp\left(\dfrac{v_{BE}}{V_T}\right) - 1 \right] \\
I_{CD} &= I_{SC} \left[ \exp\left(\dfrac{v_{BC}}{V_T}\right) - 1 \right]
\end{align}
++++


Or, using KCL to find the terminal currents:

[latexmath]
++++
\begin{align}
I_E &= &              &I_{ED} & -     \alpha_R &I_{CD} \\
I_C &= &     \alpha_F &I_{ED} & -              &I_{CD} \\
I_B &= & (1-\alpha_F) &I_{ED} & + (1-\alpha_R) &I_{CD}
\end{align}
++++

If we make the substitution latexmath:[I_S = \alpha_F I_{SE} = \alpha_R I_{SC}], the equations become:

[latexmath]
++++
\begin{align}
I_{E} &= &  \dfrac{I_S}{\alpha_F} &\left[ \exp\left(\dfrac{v_{BE}}{V_T}\right) - 1 \right] & - I_S &\left[ \exp\left(\dfrac{v_{BC}}{V_T}\right) - 1 \right] \\
I_{C} &= &  I_S &\left[ \exp\left(\dfrac{v_{BE}}{V_T}\right) - 1 \right] & - \dfrac{I_S}{\alpha_R} &\left[ \exp\left(\dfrac{v_{BC}}{V_T}\right) - 1 \right]
\end{align}
++++

Summary to this point: we have a circuit model and set of equations describing the terminal currents given the terminal voltages for a bipolar transistor.
There is no notion of _operating mode_ here; this is one set of equations and the rest is plug-and-chug.

Take a minute to also see that the above equations apply equally well to the _PNP_ in Figure <<Ebers-Moll model for PNP>>.


.Ebers-Moll model for PNP
image::Ebers-Moll_model_schematic_(PNP).svg[Ebers-Moll, 400]
// from: https://en.wikipedia.org/wiki/File:Ebers-Moll_model_schematic_(PNP).svg



=== Gummel-Poon model

The <<gummel-poon>> transistor model is an extension of the Ebers-Moll model to better match measurements and other effects.
An important aspect is that it accounts for variation in latexmath:[\beta_{F,R}] as device current changes.
It is the default bipolar transistor model used in SPICE.
A listing and brief description of the model's parameters is at the Wikipedia page https://en.wikipedia.org/wiki/Gummel%E2%80%93Poon_model[Gummel-Poon model].





=== E-M approximations

Now we will start making some approximations to arrive at some simpler equations.
The first is to drop the latexmath:[-1]`'s.
Doing this only introduces a significant error when the voltages are within a few multiples of latexmath:[V_T], or less than about 100 mV at room temperature.


[latexmath]
++++
\begin{align}
I_{E} &= &  \dfrac{I_S}{\alpha_F} &\,\exp\left(\dfrac{v_{BE}}{V_T}\right) & - I_S & \,\exp\left(\dfrac{v_{BC}}{V_T}\right) \\
I_{C} &= &  I_S & \,\exp\left(\dfrac{v_{BE}}{V_T}\right) & - \dfrac{I_S}{\alpha_R} & \,\exp\left(\dfrac{v_{BC}}{V_T}\right) \\
I_{B} &= & \dfrac{I_S}{\beta_F} &\,\exp\left(\dfrac{v_{BE}}{V_T}\right) & - \dfrac{I_S}{\beta_R} & \,\exp\left(\dfrac{v_{BC}}{V_T}\right) \\
\end{align}
++++

[#f:ebers-moll]
image::Approximated_Ebers_Moll.svg[Ebers-Moll, 400]
// from: https://commons.wikimedia.org/wiki/File:Approximated_Ebers_Moll.svg


Now, make a few *_assumptions_* for the case of an _NPN_:

* The collector is at an equal or higher potential than its emitter, latexmath:[v_C \ge v_E].

* The base is also at an equal or higher potential than the emitter, latexmath:[v_B \ge v_E].


==== Cutoff

Imagine that the base-emitter voltage is near zero (a situation when we can't ignore the latexmath:[-1], remember).
The first exponential term will be also near zero.
Also, the second exponential term's latexmath:[v_{BC}] will be near zero or negative.
This causes all of the currents to go to zero. +
-> This is _cutoff mode_.


==== Active

Next imagine that the base-emitter voltage is increased until some reasonable amount of current flows through the forward biased base-emitter _pn_ junction -- latexmath:[v_{BE}] will be around 0.6 V.
At the same time, the collector voltage is larger at some potential higher than the base, reverse biasing the base-collector junction.
The second exponential terms with latexmath:[v_{BC}] will be nearly zero under these conditions and can be ignored. +
-> This reduces to the equations for _forward active_ mode.
Notice how the collector current is not influenced by the collector voltage.

[latexmath]
++++
\begin{align}
I_E &= \frac{I_C}{\alpha_F} \\
I_C &= I_S \exp\left(\dfrac{v_{BE}}{V_T}\right) \\
I_B &= \frac{I_C}{\beta_F}
\end{align}
++++


==== Saturation

Finally, keep the base-emitter junction forward biased but keep increasing the current flowing into the base terminal by increasing latexmath:[v_{BE}].
The collector current will necessarily increase and, in a circuit, the effect will be that the collector's voltage will decrease.
See the Figure: <<bjt-saturation>> to look at this situation.
The labels will help keep the current paths straight inside the transistor.

[#bjt-saturation]
.Saturation mode current flow
image::bjt-saturation.svg[]


When the collector voltage is greater than the base voltage, diode `Dbc` is reverse-biased and therefore *Iy* is small enough to ignore.
This makes *Ib = Ix* and *Ic = Iz*, which holds until the base and collector voltages are equal.

( _slow down reading here_ )

Now increase the base voltage so *Iz* increases.
Remember the earlier relationship between base and collector currents: latexmath:[i_B = i_C / \beta_F].
This means that *Ix* and *Iz* are not independent and *Ix = Iz / &#x03b2;* as well.

*Iz* is increasing, which is lowering the collector voltage.
This causes diode `Dbc` to become forward biased and start conducting (a little) current.
*Iy* works out to be latexmath:[\frac{I_S}{\beta_R} \,\exp\left(\frac{v_{BC}}{V_T}\right)].
The collector voltage will end up at a voltage that satisfies KCL at the collector node to make *Ic = Iz - Iy*.
On the base side, you can see that *Ib = Ix + Iy*.


TIP: Is there any combination of latexmath:[\beta_F] and latexmath:[\beta_R] that allows the collector voltage to drop below the emitter voltage?


The forward biased base-collector junction's current simultaneously increases the base current and decreases the collector current from their expected values.
Since the _active_ mode simplification gives latexmath:[\beta_F = i_C / i_B], we make a new version of &beta; for saturation mode:

[latexmath]
++++
\beta_{\text{sat}} = i_C / i_B
++++


For a recap of _saturation_ mode using this new latexmath:[\beta_{\text{sat}}], remember that increasing latexmath:[i_B] does _not_ increase the collector terminal current *Ic* (it only increases both *Iz* and *Iy*).

You can see this effect by looking at Figure 16 on page 7 of ON Semiconductor's https://www.onsemi.com/pub/Collateral/2N3903-D.PDF[datasheet for the 2N3904^]:

. Each curve is for a constant collector current (set by an external constant current source).

. During the vertical part of each curve, the transistor is in _active_ mode.  For example: on the 10 mA curve at latexmath:[v_{CE} = 1.0\,\mathrm{V}], the base current is about latexmath:[80\,\mathrm{\mu A}] making latexmath:[\beta_F \approx 125] in that condition.

. As base current increases, the collector voltage does not drop much and approaches 0.1 V.

. Take Figure 16 and rotate it 90 degrees counter-clockwise so the plot shows _I_ vs. _V_.

.. Recall that the base voltage will only increase by 60 mV when the current increases by 10&times; -> in other words consider the base voltage constant.

.. The voltage axis then basically plots the voltage across diode `Dbc` and its current.  Do you see how the collector voltage drops a little to balance KCL at the collector node?






=== Hand-calculation models
There is a section at the end of most chapters in <<cmosvlsi>> called "`Pitfalls and Fallacies`" which gives some hints on where it is easy to over- or under-think an issue.
A favorite that applies to this context is:

[quote, '<<cmosvlsi>> section 2.6, page 93']
____
*Using excessively complicated models for manual calculations:*

Because models cannot be perfectly accurate, there is little value in using excessively complicated models, particularly for hand calculations.
Simpler models give more insight on key trade-offs and more rapid feedback during design.
____


The most important task is to figure out (a.k.a. guess-then-check) which mode the transistor is operating in.
Remember that it is the state of the two _pn_ junctions that determines the mode (forward or reverse).
See the table <<bjt-modes>> for a summary of these modes and the equations that are useful.


// TODO
[#bjt-hand-model-npn]
._npn_ hand model - no base current
[.left.text-left]
image::bjt-hand-model-npn.svg[]


[#bjt-hand-model-pnp]
._pnp_ hand model - no base current
[.left.text-left]
image::bjt-hand-model-pnp.svg[]

ifdef::basebackend-html[]
++++
<div style="clear: both"></div>
++++
endif::[]



[#bjt-hand-model-npn]
._npn_ hand-calculation model - including base current
[.left.text-left]
image::bjt-hand-model-npn-alt.svg[]


[#bjt-hand-model-pnp]
._pnp_ hand-calculation model - including base current
[.left.text-left]
image::bjt-hand-model-pnp-alt.svg[]


ifdef::basebackend-html[]
++++
<div style="clear: both"></div>
++++
endif::[]



==== Example {counter:example} analysis

[#ce-re]
.Example circuit with both collector and emitter resistors
image::ce-re.svg[]


For the figure <<ce-re>> use:

* *VB* = 2.0 V
* *Vcc* = 5.0 V
* *Rc* = 1 k{omega}
* *Re* = 1 k{omega}

Steps to quickly find the DC solution of this circuit:

. _Guess_ a mode -> active.
. *Vb* is known, so find *Ve* as 2.0 - 0.6 = 1.4 V.
. The voltage across *Re* is now know, so find *Ie* as 1.4 V / 1 k{omega} = 1.4 mA.
. &beta; is large (and latexmath:[\alpha_F \approx 1]), so just estimate *Ic* = *Ie*.  This is the model of <<bjt-hand-model-npn>>.
. This is enough to find the (node) voltage at the collector as (5 V - 1.4 mA &times; 1 k{omega}) = (5 - 1.4) = 3.6 V.
. That's it! ... wait, not until we check the mode:
.. *Vc* > *Vb* so `Q1` is indeed in _active_ mode.
.. Done.


Open up https://www.circuitlab.com/circuit/67u5zus59rhy/ce-re-example/[CircuitLab schematic *ce-re-example*^] and run a DC Simulation.
Click on the nodes and device terminals to see the various node voltages and currents.

NOTE: Notice that the simulator (which is SPICE underneath) reports the emitter current as negative.
It turns out that SPICE defines all device currents as positive into the terminals.
Also notice that the current changes sign when probing the current at either end of a resistor.
Here also, SPICE uses _polarized_ resistors, which is basically the + and - terminals are defined graphically before simulation.



==== Example {counter:example}

Keep the same conditions as above, except change:

* *Rc* => 10 k{omega}

Not much changes on the emitter side of the circuit, so no need to re-do the math.

. Find *Vc* as (5 V - 1.4 mA &times; 10 k{omega}) = (5 - 14.0) = -9.0 V.
. The first clue is a negative node voltage when there are no negative supply voltages.
. The second is to check the operation mode:
.. *Vb* > *Ve* so the B-E junction is forward biased.  (no surprise since we forced this)
.. *Vc* < *Vb* so the B-C junction is also forward biased.  This violates our starting assumption of _active_ mode.  The solution is to re-do the problem but assume a different mode (_saturation_).


Take another swig of coffee and start over.
Oh wait, _saturation_ only changes the collector side.
All of the emitter side math stays the same.

. Set *Vce* to 0.1 V according to the table.
. Therefore *Vc* is 1.5 V.
. *Ic* calculates to (5.0 - 1.5) / 10 k{omega} = 0.35 mA.
. If it is useful, we can use KCL to compute the base current as *Ie* - *Ic* = 1.05 mA.
. The check is to see if base current is larger than what is predicted by latexmath:[\beta_F].  It is obviously larger than *Ic / &beta;*, so the check passes.

Check that these numbers are close to what is simulated (which uses the <<Gummel-Poon model>>) in the same CircuitLab schematic as the first example.


Finally, compute latexmath:[\beta_{\text{sat}} = 0.35 / 1.40 = 0.25].
This number is useful to see how _deep into saturation_ the transistor is.
Here, it is approximately ocean-floor-deep _saturation_ mode.



=== Rules of thumb

==== Ratio rules
Assuming two transistors are _matched_ (their parameters such as I~S~ and temperature are exactly the same):

* stem:[\dfrac{I_{C2}}{I_{C1}} = \exp\left(\dfrac{\Delta V_{BE}}{V_T}\right)]
* stem:[\Delta V_{BE} = V_T \ln\left( \dfrac{I_{C2}}{I_{C1}} \right)]


==== Temperature dependence
[positive emphatic slang here], this is an important topic!
IM__NSH__O, properly dealing with temperature dependence over the entire range of intended operational temperatures separates the professional from the amateur circuit designer.

.When talking about your designs:
[quote, Anyone (except you of course)]
It *just works* ... always.


It may seem from <<_ratio_rules>> that temperature only shows up as stem:[V_T = \frac{k_B\,T}{q}].
Remember that the saturation current I~S~ is also a strong function of temperature (T^4^&nbsp;!).
The following relationships work well over nearly the entire electronics temperature ranges (very cold is _interesting_ to Physicists, and much hotter and things start melting):

Constant I~C~::
* stem:[\Delta V_{BE} \approx -2.1 \,\mathrm{mV / ^\circ C}]
* stem:[\propto 1 / T\,\mathrm{(K)}]

Constant V~BE~::
* stem:[\Delta I_C \approx 9\,\mathrm{\% / ^\circ C}]
* stem:[2\!\times I_C \text{ for } \Delta T = 8\,\mathrm{^\circ C}]






image::ce-basic.svg[]



ifeval::["{docname}" != "guidebook"]
include::refs.adoc[]
endif::[]

