= Bipolar transistor operation

:sect: &#167;

'''
[#2018-01-10]

Bipolar transistors are named as such because both _electrons_ and _holes_ participate in the device's operation.


== Useful tables

NOTE: This section is at the top of the page for quick reference.


[#bjt-modes]
.Bipolar transistor modes
[cols=".^1,.^1,.^1,.^7"]
|===
|B-E junction |B-C junction |Mode |Equations

|Reverse
|Reverse
|cutoff
|latexmath:[
\begin{cases}
i_C \approx 0 \\
i_B \approx 0
\end{cases}
]

|Forward
|Forward
|saturation
|latexmath:[
\begin{cases}
V_{BE} \approx 0.6 V \\
V_{CE} = V_{CE sat} \approx 0.2 V \\
i_C \rightarrow \text{set by circuit conditions} \\
i_B \rightarrow \text{must be } > I_C/\beta
\end{cases}
]

|Forward
|Reverse
|active
|latexmath:[
\begin{cases}
V_{BE} \approx 0.6 V \\
V_{CE} \rightarrow \text{set by circuit conditions} \\
i_C = \begin{cases}
        \alpha \, i_E \\
        \beta \, i_B \\
        I_S \exp \left( v_{BE} / V_T \right)
      \end{cases} \\
i_B = i_C / \beta \\
\end{cases}
]

|Reverse
|Forward
|rev-active
|(your transistor is in backwards)

|===




'''



[#bjt-parameters]
.Transistor parameter definitions
[cols=".^1,.^3,.^5"]
|===
| Term | Name | Definition

|latexmath:[\beta]
|common-emitter current gain
|latexmath:[\dfrac{i_C}{i_B} = \dfrac{\beta}{1 + \beta}]

|latexmath:[\alpha]
|common-base current gain
|latexmath:[\dfrac{i_C}{i_E} = \dfrac{\alpha}{1 - \alpha}]

|latexmath:[V_T]
|thermal voltage
|latexmath:[\dfrac{k_B T}{q}]

|===



== Structure and Physics

Figure <<bjt-planar>> shows the side view of an _npn_ BJT as it would be fabricated on a chip.
The _order_ of the three-layer sandwich determines the *type* (_npn_ or _pnp_), while the _doping level_ of the outer layers determines the **C**ollector and **E**mitter terminal labels.


[#bjt-planar]
.Cross section of a planar BJT
image::NPN_BJT_(Planar)_Cross-section.svg[]
// from: https://en.wikipedia.org/wiki/File:NPN_BJT_(Planar)_Cross-section.svg
// modified emitter to add "+" to doping

[#bjt-current-flow]
.Bipolar current flow in active mode
image::NPN_BJT_Basic_Operation_(Active).svg[]
// from: https://en.wikipedia.org/wiki/File:NPN_BJT_Basic_Operation_(Active).svg



NOTE: This is a note


TIP: This is a tip


IMPORTANT: This is important.


CAUTION: This is a caution.


WARNING: This is a warning.





.Where can I read more?
****
* The Wikipedia page https://en.wikipedia.org/wiki/Bipolar_junction_transistor[Bipolar junction transistor]

****



== Circuit Models

=== Ebers-Moll model

The Ebers-Moll model is accurate, useful, and therefore well-known.
It accounts for normal _pn_ junction current flow and the "`transistor action`" current flow due to the shared middle region.


.Ebers-Moll model for NPN
image::Ebers-Moll_model_schematic_(NPN).svg[Ebers-Moll, 400]
// from: https://en.wikipedia.org/wiki/File:Ebers-Moll_model_schematic_(NPN).svg

Ebers-Moll model for NPN
The diode currents for Figure <<Ebers-Moll model for NPN>> are found in the normal way by their voltages:

[latexmath]
++++
\begin{align}
I_{ED} &= I_{SE} \left[ \exp\left(\dfrac{v_{BE}}{V_T}\right) - 1 \right] \\
I_{CD} &= I_{SC} \left[ \exp\left(\dfrac{v_{BC}}{V_T}\right) - 1 \right]
\end{align}
++++


Or, using KCL to find the terminal currents:

[latexmath]
++++
\begin{align}
I_E &= &              &I_{ED} & -     \alpha_R &I_{CD} \\
I_C &= &     \alpha_F &I_{ED} & -              &I_{CD} \\
I_B &= & (1-\alpha_F) &I_{ED} & + (1-\alpha_R) &I_{CD}
\end{align}
++++

If we make the substitution latexmath:[I_S = \alpha_F I_{SE} = \alpha_R I_{SC}], the equations become:

[latexmath]
++++
\begin{align}
I_{E} &= &  \dfrac{I_S}{\alpha_F} &\left[ \exp\left(\dfrac{v_{BE}}{V_T}\right) - 1 \right] & - I_S &\left[ \exp\left(\dfrac{v_{BC}}{V_T}\right) - 1 \right] \\
I_{C} &= &  I_S &\left[ \exp\left(\dfrac{v_{BE}}{V_T}\right) - 1 \right] & - \dfrac{I_S}{\alpha_R} &\left[ \exp\left(\dfrac{v_{BC}}{V_T}\right) - 1 \right]
\end{align}
++++

Summary to this point: we have a circuit model and set of equations describing the terminal currents given the terminal voltages for a bipolar transistor.
There is no notion of _operating mode_ here; this is one set of equations and the rest is plug-and-chug.

Take a minute to also see that the above equations apply equally well to the _PNP_ in Figure <<Ebers-Moll model for PNP>>.


.Ebers-Moll model for PNP
image::Ebers-Moll_model_schematic_(PNP).svg[Ebers-Moll, 400]
// from: https://en.wikipedia.org/wiki/File:Ebers-Moll_model_schematic_(PNP).svg



=== E-M approximations

Now we will start making some approximations to arrive at some simpler equations.
The first is to drop the latexmath:[-1]`'s.
Doing this only introduces a significant error when the voltages are within a few multiples of latexmath:[V_T], or less than about 100 mV at room temperature.


[latexmath]
++++
\begin{align}
I_{E} &= &  \dfrac{I_S}{\alpha_F} &\,\exp\left(\dfrac{v_{BE}}{V_T}\right) & - I_S & \,\exp\left(\dfrac{v_{BC}}{V_T}\right) \\
I_{C} &= &  I_S & \,\exp\left(\dfrac{v_{BE}}{V_T}\right) & - \dfrac{I_S}{\alpha_R} & \,\exp\left(\dfrac{v_{BC}}{V_T}\right) \\
I_{B} &= & \dfrac{I_S}{\beta_F} &\,\exp\left(\dfrac{v_{BE}}{V_T}\right) & - \dfrac{I_S}{\beta_R} & \,\exp\left(\dfrac{v_{BC}}{V_T}\right) \\
\end{align}
++++

[#f:ebers-moll]
image::Approximated_Ebers_Moll.svg[Ebers-Moll, 400]
// from: https://commons.wikimedia.org/wiki/File:Approximated_Ebers_Moll.svg


Now, make a few *_assumptions_* for the case of an _NPN_:

* The collector is at an equal or higher potential than its emitter, latexmath:[v_C \ge v_E].

* The base is also at an equal or higher potential than the emitter, latexmath:[v_B \ge v_E].


Imagine that the base-emitter voltage is near zero (a situation when we can't ignore the latexmath:[-1], remember).
The first exponential term will be also near zero.
Also, the second exponential term's latexmath:[v_{BC}] will be near zero or negative.
This causes all of the currents to go to zero. +
-> This is _cutoff mode_.

Next imagine that the base-emitter voltage is increased until some reasonable amount of current flows through the forward biased base-emitter _pn_ junction -- latexmath:[v_{BE}] will be around 0.6 V.
At the same time, the collector voltage is larger at some potential higher than the base, reverse biasing the base-collector junction.
The second exponential terms with latexmath:[v_{BC}] will be nearly zero under these conditions and can be ignored. +
-> This reduces to the equations for _forward active_ mode.
Notice how the collector current is not influenced by the collector voltage.

[latexmath]
++++
\begin{align}
I_E &= \frac{I_C}{\alpha_F} \\
I_C &= I_S \exp\left(\dfrac{v_{BE}}{V_T}\right) \\
I_B &= \frac{I_C}{\beta_F}
\end{align}
++++


Finally, keep the base-emitter junction forward biased but keep increasing the current flowing into the base terminal by increasing latexmath:[v_{BE}].
The collector current will necessarily increase and, in a circuit, the effect will be that the collector's voltage will decrease.
See the Figure: <<bjt-saturation>> to look at this situation.
The labels will help keep the current paths straight inside the transistor.

[#bjt-saturation]
.Saturation mode current flow
image::bjt-saturation.svg[]


When the collector voltage is greater than the base voltage, diode `Dbc` is reverse-biased and therefore *Iy* is small enough to ignore.
This makes *Ib = Ix* and *Ic = Iz*, which holds until the base and collector voltages are equal.

[ slow down reading here ]

Now increase the base voltage so *Iz* increases.
Remember the earlier relationship between base and collector currents: latexmath:[i_B = i_C / \beta_F].
This means that *Ix* and *Iz* are not independent and *Ix = Iz / &#x03b2;* as well.

*Iz* is increasing, which is lowering the collector voltage.
This causes diode `Dbc` to become forward biased and start conducting (a little) current.
*Iy* works out to be latexmath:[\frac{I_S}{\beta_R} \,\exp\left(\frac{v_{BC}}{V_T}\right)].
The collector voltage will end up at a voltage that satisfies KCL at the collector node to make *Ic = Iz - Iy*.
On the base side, you can see that *Ib = Ix + Iy*.

The forward biased base-collector junction's current simultaneously increases the base current and decreases the collector current from their expected values.


TIP: Is there any combination of latexmath:[\beta_F] and latexmath:[\beta_R] that allows the collector voltage to drop below the emitter voltage?








//[#bjt-large-signal-model]
//image::bjt-large-signal-model.svg[]


=== Gummel-Poon model

The <<gummel-poon>> transistor model is an extension of the Ebers-Moll model to better match measurements and other effects.
An important aspect is that it accounts for variation in latexmath:[\beta_{F,R}] as device current changes.
It is the default bipolar transistor model used in SPICE.
A listing and brief description of the model's parameters is at the Wikipedia page https://en.wikipedia.org/wiki/Gummel%E2%80%93Poon_model[Gummel-Poon model].





=== Shortcuts

There is a section at the end of most chapters in <<cmosvlsi>> called "`Pitfalls and Fallacies`" which gives some hints on where it is easy to over- or under-think an issue.
A favorite that applies to this context is:

[quote, '<<cmosvlsi>> section 2.6, page 93']
____
*Using excessively complicated models for manual calculations:*

Because models cannot be perfectly accurate, there is little value in using excessively complicated models, particularly for hand calculations.
Simpler models give more insight on key trade-offs and more rapid feedback during design.
____


The most important task is to figure out (a.k.a. guess-then-check) which mode the transistor is operating in.
Remember that it is the state of the two _pn_ junctions that determines the mode (forward or reverse).
See the table <<bjt-modes>> for a summary of these modes and the equations that are useful.


==== Example analysis

[#ce-re]
.Example circuit with both collector and emitter resistors
image::ce-re.svg[]





image::ce-basic.svg[]







[bibliography]
== References

- [[[cmosvlsi, CMOS VLSI]]] Neil Weste and David Harris, _CMOS VLSI Design - A Circuit and Systems Perspective_, 4th edition. Addison-Wesley, 2011

- [[[gummel-poon, Gummel-Poon]]] H.K. Gummel, H.C. Poon, An Integral Charge Control Model of Bipolar Transistors.  Bell System Technical Journal, 49: 5. May-June 1970 pp 827-852. https://archive.org/details/bstj49-5-827

