= hw07
:stem: stem
:xrefstyle: full
:sectnums:



Submit either on paper or via Blackboard.


[#ce-amp]
.CE amplifier
image::ce-amp.svg[]


== Common-emitter amplifier bias design

For the circuit of <<ce-amp>>, select standard values from the https://en.wikipedia.org/wiki/E_series_of_preferred_numbers#Lists[E12 series^] for the resistors to set the following DC bias conditions to within 10%.
Report your values in the table and also the predicted collector currents given your selected resistor values.
Use V~CC~ = 10 V.

* Voltage across `Re` is between 1&times; and 2&times; V~BE~.
* `Q1` collector current is about 5 mA.
* The collector voltage V~C~ is the middle point of the range where `Q1` is in forward-active mode.
* The total power supply current is 7 mA or less.



.Folded cascode values
[cols="1,4"]
|===
| Device | Value (units)

| R1
|

| R2
|

| Rc
|

| Re
|

|I~C1~
|

|===


<<<
[#folded-cascode]
.CE + CB - folded cascode amplifier
image::folded-cascode.svg[]




== Folded cascode amplfier bias design

For the circuit of <<folded-cascode>>, select standard values from the https://en.wikipedia.org/wiki/E_series_of_preferred_numbers#Lists[E12 series^] for the resistors to set the following DC bias conditions to within 10%.
Report your values in the table and also the predicted collector currents given your selected resistor values.

* V~OUT~ = 1.8 V
* Q1-C and Q2-E node voltage = 3.5 V
* Q1 and Q2 collector currents = 1 mA



.Folded cascode values
[cols="1,4"]
|===
| Device | Value (units)

| R1
|

| R2
|

| R3
|

| R4
|

| R5
|

| R6
|

| R7
|

|I~C1~
|

|I~C2~
|

|===





// vim: tw=0
