= hw08
:stem: stem
:xrefstyle: full

ifeval::["{docname}" != "guidebook"]
include::subs.adoc[]
endif::[]


Due Wednesday 2018-04-04 at the start of class.





== TI Precision Labs - Op Amps

* [ ] Go to https://training.ti.com/ti-precision-labs-op-amps[TI Precision Labs - Op Amps videos^] and setup a free myTI account to access all of the videos.

* [ ] Watch the video *_1.1 TI Precision Labs - Op Amps: Introduction_*
* [ ] Watch both videos in section *_2. TI Precision Labs - Op Amps: Input Offset Voltage and Input Bias Current_*

** Be prepared to take a short quiz about section 2 at the start of class Wednesday.

* [ ] Watch the videos in section *_3. TI Precision Labs - Op Amps: Input and Output Limitations_*


FYI, you will also be watching the videos in sections 5, 6, and 7 in the _very near future_.



== Lab 5 analysis
Take the results from measurements of <<lab5.adoc#connections,Figure 4, Amplifier connections>> to find the following performance metrics of your op amp:

* V~os~
* I~b+~
* I~b-~
* I~os~

Use the handout from Monday https://drive.google.com/open?id=1t55H5bQRUBX6z7pMjigNy-jK-ZiIKJZ6Sy2YIXo6DBU[2018-04-02_notes^] as your definitions of the above terms.



== Notes
**Hand in your work on ENGINEERING PAPER:**footnote:[I will hand your paper back without grading for you to actually re-write!]

* One side of writing per page.
* One column of intermixed schematic, math, and text.
* Near-zero cross-outs or erase marks.  (you have plenty of paper!)footnote:[See Prof. White if you didn't receive your _complementary_ pad of engineering paper.]











// vim: tw=0
