= Lab 1-A: Emitter Follower
:stem: stem

ifeval::["{docname}" != "guidebook"]
include::subs.adoc[]
endif::[]




[#f-phase-splitter]
.Schematic of a phase-splitter
image::phase-splitter-lab1a.svg[]


== Lab goals

Topics::

* Identifying transistor operating modes (_cutoff_, _active_, _saturation_) by looking at circuit waveforms.
* Quickly building and measuring small transistor circuits with minimal wiring errors.


Each of the two lab sections are doing different activities!

Your task is to learn about the concepts using <<f-phase-splitter>> as your example and be able to help your classmates who did the other activity.
The focus topics are similar between the two sections, however.
This allows everyone several angles by which to learn the concepts.
A secondary goal is to increase your technical communication / teaching skills through action.


<<<

== Activities

Begin with only the circut in <<f-phase-splitter>> contained inside the *Step 1* box.

Set `Rc` to 100&ohm; for this lab.


=== DC conditions
Select values of `R1` and `R2` to make the emitter voltage near 0 V.

* [ ] What is therefore the required base node voltage?

You want the current through `R1` and `R2` to be 10&times; to 20&times; larger than the transistor's base current.


[TIP]
====
*Why?*
To make the DC operating condition less sensitive to the highly-variable transistor properties like &beta;. 

This allows us to ignore base current (which incurs a <10% error) for quickly designing a voltage divider for the base node.
Because the actual base current is small compared to the V-divider current, the in-circuit base voltage is still close to the desired value.
====

*How* to do this?

* [ ] What is the emitter current?
* [ ] Estimate the base current.  (see <<bjt-review.adoc#bjt-parameters,Table "`Transistor parameter definitions`">> for a hint.

10&times; to 20&times; this base current is then your target current through `R1`.

* [ ] Find a `R1` value that meets this condition and is in stock.footnoteref:[e12,The GEM 163 storage cabinet has every https://en.wikipedia.org/wiki/E-series_of_preferred_numbers#Lists[E12 series] value from 1 &ohm; to 10 M&ohm;]
* [ ] Calculate the required `R2` value and round to a value that is in stock.footnoteref:[e12]

&rarr; Alternate way to find `R1` and `R2`: view as a voltage divider and use the link:tools/v-divider.html[*Best Voltage divider resistor calculator ever* at agnd.net^]

Build this circuit and verify that the emitter voltage is indeed near 0 V.


<<<
=== Amplifier

Now setup the circuit contained in the *Step 2* box.
Use the bench-top function generator or *AD2* function generator output `W1` as source _V~s~_

Use oscilloscope channel 1 to view the node voltage at *B* (between *B* and zero) and channel 2 to view *out*.

Set an initial amplitude of 200 mV peak-to-peak.  A triangle is likely the most useful shape.

Verify that the amplifier is working as a voltage follower.


Now, increase the input signal amplitude until the output voltage starts to have some "`issues`" (no longer a triangle, clipping, etc.).
//Set the amplitude to 6 V peak-to-peak.


* Your task is to figure out *why* the output looks the way it does!
** See <<_lab_goals>> if you need a hint!
* Then you should make a short document to yourself describing what you did and your explanation of the last waveforms.  Something that you can give a friend to get them up to speed on the behavior.


// don't display until after the lab session!
//ifdef::DISABLED[]
.Circuit notes
****
The amplifier's output voltage will track the input voltage with about a 0.7 V
downward shift (V~BE~).
However, at large amplitudes, the output will clip at about -1.5 V.

As the input (base) voltage and therefore output / emitter voltage decreases, the emitter current decreases.
This current is easily found by fixing V~E~ and solving for the currents at the emitter node via KCL.
Emitter current eventually reaches zero and will not become negative because the transistor is now in _cutoff_ mode.  
The equivalent circuit at node *out* in this condition is merely a voltage divider between *-5 V* and zero involving `Re` and `Rload`.

Section 2.2.3.D of <<AoE>> also discusses this behavior of a resistively-biased *EF*.
In addition, <<L-AoE>> sections 4N.4.4 and 4N.4.5 add some nice explanation and points out the power dissipation problem that rears its head as soon as you try to get more voltage swing by lowering `Re`.
****
//endif::[]


//ifeval::["{docname}" != "guidebook"]
//include::refs.adoc[]
//endif::[]

// vim: tw=0
