= Lab 3-A: CE amplifier
:stem: stem

ifeval::["{docname}" != "guidebook"]
include::subs.adoc[]
endif::[]


[#ce-amp]
.CE amplifier schematic
image::ce-amp.svg[]




== Lab goals

Topics::

* Verify your link:hw07.html[`hw07`^] (DC) bias condition solution for this circuit.

* Measure amplifer parameters, R~in~, R~out~, A~V0~.

* Amplifier AC gain prediction, measurement, and calculation.


*Your task* is to match measured amplifier parameters to those predicted by small-signal analysis.

* Measurements of a prototype build of the circuit.

* Predictions of amplifier gain using the link:bjt-amplifiers.adoc#bjt-amplifiers[Bipolar transistor amplifier types^] table techniques.




== DC bias solution and setup

Build <<ce-amp>> using your values for `R1`, `R2`, `Rc`, and `Re` with V~CC~ = 10 V.

Add one or two power supply bypass capacitors (0.1 to 10 &mu;F).
These are placed physically close to your circuit and between the power supply nodes.
Use one if using a single +10 V supply.
If using dual &pm;5 V supplies, place one capacitor between +5 V and the reference node and a second between the reference node and -5 V.

Measure the `B`, `C`, and `E` DC node voltages to verify that they match your hand calculations.

https://www.circuitlab.com/circuit/4qqa7q3tm34f/ce-amp_math/[CE amplfier schematic in CircuitLab^]


== Capacitor selection

It is useful to have the frequency response of an amplifier set in a limited number of positions.
This circuit has 2 high-pass filters with `Cin` and `Cout`, and a pole/zero pair that is related to `Ce`.

*TODO* do not place `Ce` for the measurements.  Gain is way too high for a good lab experience.

* [ ] Set the value of `Ce` to be greater than the value that makes the impedance magnitude of `Re` and `Ce` equal at 100 Hz.

stem:[|Z_{Ce}| = \dfrac{1}{2\pi f C_e}]


Therefore, at frequencies greater than 100 Hz, the parallel combination of `Ce` and `Re` will be essentially the impedance of `Ce` alone (which is also the table's stem:[Z_E]).
Note that the stem:[Z_E] also interacts with stem:[r_e] for the common-emitter's open-circuit voltage gain stem:[A_{v\emptyset}] in <<bjt-amplifiers.adoc#bjt-amplifiers,Table 6. Bipolar transistor amplifier types>>.
This indicates that the gain will no longer increase with increasing frequency once stem:[Z_E] is smaller than stem:[r_e].

Capacitor `Cin` in the input circuit creates a 1^st^-order high-pass filter in combination with the source's output impedance and the amplifier's input impedance.
The resistance for computing this time constant (or corner frequency) is the that seen by the capacitor, which is (`Rs` + `Rin`).

* [ ] For now, estimate `Rin` as `R1` || `R2` and select a value for `Cin` that makes the corner (-3 dB) frequency of this filter around 10 Hz.

* [ ] Select `Cout` to be the same value as `Cin` (for now).


== Amplifier operation

Connect a function generator for `Vs` with a sinusoid at a frequency of *10 kHz*.
The benchtop generators already have an internal `Rs` of 50 &ohm;.
If you are using an AD2, add a 47 &ohm; series resistor for `Rs`.

Probe both the input node (left side of `Cin` and output node (your probe's input impedance is R~load~.

* [ ] Find the maximum amplitude your input can have before the output waveform is no longer also a sinusoid.
* [ ] Compute the magnitude of the voltage gain of your amplifier by: stem:[A_{v\emptyset} = \dfrac{|v_{out}|}{|v_{in}|}] from your measurements at this amplitude.
* [ ] Reduce your input amplitude and verify that the output amplitude reduces proportionally.  (_This is the very definition of linear_)

For all of these measurements, continue to monitor the output waveform for clipping.
All transistors must remain in forward-active mode at all times to be able to match circuit measurements to parameters predicted by the small-signal model.


What is the *sign* of the voltage gain?  (Are the input and output waveforms in-phase or inverse of each other)


* [ ] Devise and carry out a procedure to infer by measurements your amplifier's input resistance `Rin`.  Ensure that the frequency you are testing at makes the assumption that the capacitors are short-circuits remains valid!  Changing resistors and test conditions may violate these assumptions.
* [ ] By the same sort of procedure, estimate your amplifier's output resistance `Rout`.


At this point, you have numbers for `Rin`, `Rout` and `Av0`.
These numbers should match those obtained from small-signal circuit analysis of the same circuit.


== Frequency response

(If you are using an AD2)

Start *WaveForms* and select the *Network* module.

This feature allows you to measure transfer functions (both magnitude and phase) by sweeping the signal generator's frequency and measuring both the input and output, which gives sufficient information to compute these numbers.
The software displays these measurements as a function of frequency.

Configure the Wavegen settings so the *Amplitude* is about 1/2 of the maximum input amplitude determined earlier.

Connect Ch1 to the input node and Ch2 to the output node.

Vary the start and stop frequencies (top bar) to see both the high and lower frequency limits of your amplifier.


Replace `Cin` with a value 100&times; smaller and notice the change in frequency response.
















// vim: tw=0
