= Differential terminology
:stem: stem
:eqnums:





//----
//CA3046
//CA3086
//----


[#diff-pair]
.Differential-pair schematic
image::diff-pair.svg[alt,450]



Differential signaling using a pair of wires is highly useful for sending signals between circuits.
It makes it possible to remove several types of noise and interference added to the signal along its path from transmitter to receiver.
USB and wired Ethernet connections are common examples of differential signaling in practice.

The desired signal is applied as the difference between the two wires and, ideally, the noise voltages/currents are added equally and in-phase to each conductor of the pair.
The receiver simply takes the difference of the pair as the signal quantity, therefore removing all of the noise.

<<<

There are 3 nodes that participate in a differential pair of signals:  a common reference defined at the receiver's end of the circuit, and the two signal nodes A and B (or [+in and -in],  or [inp and inm])
The node voltages Va and Vb (measured with respect to the circuit's reference node) completely describe the values.

However, it is much more useful to define another set of quantities:

[stem]
++++
\begin{align}
v_D &= v_A - v_B \\
v_{CM} &= (v_A + v_B) / 2
\end{align}
++++


Given the set of differential and common-mode voltages for a pair of nodes, it is a small matter of algebra to know the individual node voltages:

[stem]
++++
\begin{align}
v_A &= v_{CM} + v_D / 2 \\
v_B &= v_{CM} - v_D / 2 \\
\end{align}
++++


See <<terms>> for a graphical version of these conversion equations.

[#terms]
.Two ways of specifying the voltage at a pair of nodes.
image::diff-cm-terms.svg[alt,300]



Some additional points to remember::
* In both systems, two terms are required to completely specify the potentials at the two nodes.
* The equations use terms in lower~UPPER~ notation, the total or physical quantity, to emphasize that these two systems are always valid.
* ... meaning they are also valid for DC quanitities (UPPER~UPPER~ notation) and for small-signal quantities (lower~lower~ notation).







== Lab goals







ifeval::["{docname}" != "guidebook"]
include::refs.adoc[]
endif::[]

// vim: tw=0
