= Lab 4: Differential and common-mode in a differential-pair
:stem: stem
:eqnums:





//----
//CA3046
//CA3086
//----



Differential signaling using a pair of wires is highly useful for sending signals between circuits.
It makes it possible to remove several types of noise and interference added to the signal along its path from transmitter to receiver.
USB and wired Ethernet connections are common examples of differential signaling in practice.

The desired signal is applied as the difference between the two wires and, ideally, the noise voltages/currents are added equally and in-phase to each conductor of the pair.
The receiver simply takes the difference of the pair as the signal quantity, therefore removing all of the noise.

<<<

There are 3 nodes that participate in a differential pair of signals:  a common reference defined at the receiver's end of the circuit, and the two signal nodes A and B (or [+in and -in],  or [inp and inm])
The node voltages Va and Vb (measured with respect to the circuit's reference node) completely describe the values.

However, it is much more useful to define another set of quantities:

[stem]
++++
\begin{align}
v_D &= v_A - v_B \\
v_{CM} &= (v_A + v_B) / 2
\end{align}
++++


Given the set of differential and common-mode voltages for a pair of nodes, it is a small matter of algebra to know the individual node voltages:

[stem]
++++
\begin{align}
v_A &= v_{CM} + v_D / 2 \\
v_B &= v_{CM} - v_D / 2 \\
\end{align}
++++


See <<terms>> for a graphical version of these conversion equations.

[#terms]
.Two ways of specifying the voltage at a pair of nodes.
image::diff-cm-terms.svg[alt,300]



Some additional points to remember::
* In both systems, two terms are required to completely specify the potentials at the two nodes.
* The equations use terms in lower~UPPER~ notation, the total or physical quantity, to emphasize that these two systems are always valid.
* ... meaning they are also valid for DC quanitities (UPPER~UPPER~ notation) and for small-signal quantities (lower~lower~ notation).







== Lab goals

[#diff-pair]
.Differential-pair schematic
image::diff-pair.svg[]



//TODO
Reminder:  we are using the AD2 specifically because they are able to output two phase-locked waveforms and the input channels are differential.  There is no need to use "Math" to subtract channel 2 from channel 1 → just directly attach the two wires of each channel to the two nodes that are to be subtracted.





== Procedure

=== DC conditions

Make these measurements to no more than 3 digits of precision.
Only in section 2.4 should you need to use the Keysight multimeters.

* [ ] Build the circuit of <<diff-pair>>.

* [ ] Apply 0 V to both inputs ina and inb.


Measure the node voltages and currents through the 3 resistors: 

[#measurements]
.DC Measurements
[cols="^1,^3"]
|===
|Name
|Value

|V~outA~
|

|V~outB~
|

|V~E~
|

|I~R1~
|

|I~R2~
|

|I~RE~
|

|===




== Amplifier measurements
. Configure the AD2's function generators to output a pair of signals which yield a pure common-mode signal of:

[stem]
++++
\begin{align}
v_{in,\, cm}(t) &= 2\,\sin(2\pi 1000 t) \;\mathrm{V}\\
v_{in,\, d}(t) &= 0 \;\mathrm{V}
\end{align}
++++

* Be sure to configure the *Wavegen* for the AD2's _Waveforms_ software from "No synchronization" to "Auto synchronization".  This ensures that both signal generators start at exactly the same time.  Weird waveforms will be the result if your forget this!

[start=2]
. Measure the three common-mode voltage gains in this circuit.
    * These are the signal amplitudes, in volts peak-to-peak or volts RMS (preferred), +
      &rarr; do NOT use "Math" to divide one oscilloscope channel by the other.
    * You can predict the first two single-ended gains by viewing the circuit two separate common-emitter amplifiers with emitter resistor values of 2R~E~ (&approx; &minus; R~c~ / 2R~E~).
    * Predict the common to differential mode gains by thinking about the circuit's symmetry.


[stem]
.Common-mode to single-ended gains
++++
\begin{align}
    A_{cm\,A} &= v_{outA} / v_{in,\,cm} \\
    A_{cm\,B} &= v_{outB} / v_{in,\,cm} \\
\end{align}
++++

[stem]
.Common-mode to differential mode conversion gain
++++
A_{cm} = v_{out,\,d} / v_{in,\,cm} = (v_{outA} - v_{outB}) / v_{in,\,cm}
++++

* Measuring the differential output stem:[v_{out,\,d}] is where you can use the fact that the AD2's input channels are _differential_.
  There is no need, like there is with a benchtop oscilloscope, to use two probes, one for each node A and B, and then subtract the channels using the *Math* function.
  Simply connect the &plus; and &minus; leads of the AD2 channel directly across nodes *outA* and *outB*.



[start=3]
. Configure the AD2's function generators to output a pure differential triangular signal of:

[stem]
++++
\begin{align}
v_{in,\, cm}(t) &= 0 \;\mathrm{V} \\
v_{in,\, d}(t) &= 0.3\, \operatorname{tri}(2\pi 1000 t) \;\mathrm{V}
\end{align}
++++


[start=4]
. Plot the large-signal differential-input to differential-output transfer function using an X-Y display, stem:[(V_{outA} - V_{outB}) \text{  versus  }   V_{in,\,d}].

. From this X-Y plot, determine the maximum differential input amplitude that still gives an un-distorted differential output signal.  (hint: it will be within a small factor of the thermal voltage stem:[V_T])

. Reduce the differential input amplitude to this value and measure the following gains.  They will be about 90 or 180 V/V.

[stem]
++++
\begin{align}
A_{d,\,A} &= v_{outA} / v_{in,\,d}\\
A_{d,\,B} &= v_{outB} / v_{in,\,d}\\
A_{d}     &=  (v_{outA} - v_{outB}) / v_{in,\,d}
\end{align}
++++

--

<<<



[#diff-pair2]
.Differential-pair with tail current source schematic
image::diff-pair2.svg[alt,500]


[start=7]
. Build the circuit of <<diff-pair2>>.

. Determine the closest E12 value for *R3* to give the same current as was through *R~E~*.  Verify this current by measurement.  Hint: what is the voltage across *R3*?



. Measure the same six gains on this circuit as on <<diff-pair>> (three stem:[A_{cm}] variations and three stem:[A_d] variations).

. Measure input currents and the base-emitter voltages.
    Place a 10k resistor in series with the bases of each of Q1 and Q2.
    Set stem:[v_{i,\,cm} = 0] and stem:[v_{i,\,d} = 0] using the function generators.
    Measure the base currents of Q1 and Q2 by measuring the DC voltage drop across the series resistors.
    This is a great opportunity to use the nice, new, Keysight meters! 



[#measurements2]
.Diff-pair DC measurements
[cols="^1,^3"]
|===
|Name
|Value

|I~B1~
|

|I~B2~
|

|V~BE1~
|

|V~BE2~
|


|===




--



















ifeval::["{docname}" != "guidebook"]
include::refs.adoc[]
endif::[]

// vim: tw=0
