[bibliography]
== References

- [[[AoE]]] P. Horowitz and W. Hill,
  _The Art of Electronics_, 3rd ed.
  Cambridge University Press, 2015.
  https://artofelectronics.net[^]

- [[[L-AoE]]] T. Hayes,
  _Learning the Art of Electronics: A Hands-On Lab Course_,
  Cambridge University Press, 2016.
  https://learningtheartofelectronics.com[^]

- [[[LEC]]] Tony R. Kuphaldt, _Lessons in Electric Circuits_,
    Source version: https://www.ibiblio.org/kuphaldt/electricCircuits/,
    All About Circuits version: https://www.allaboutcircuits.com/textbook/

- [[[CL-book]]] Michael F. Robbins, CircuitLab,
  _Ultimate Electronics: Practical Circuit Design and Analysis_,
  https://www.circuitlab.com/textbook/

- [[[TCA]]] Alfred D. Gronner,
  _Transistor Circuit Analysis_,
  Simon & Schuster, 1970,
  https://archive.org/details/TransistorCircuitAnalysis

- [[[cmosvlsi, CMOS VLSI]]] Neil Weste and David Harris,
  _CMOS VLSI Design - A Circuit and Systems Perspective_, 4th edition.
  Addison-Wesley, 2011.
  http://pages.hmc.edu/harris/cmosvlsi/4e/index.html[^]

- [[[Guidebook]]] D. White,
  _Guidebook for Electronics II_.
  https://agnd.net/valpo/341/guidebook[^]

- [[[gummel-poon, Gummel-Poon]]] H.K. Gummel, H.C. Poon,
  _An Integral Charge Control Model of Bipolar Transistors_.
  Bell System Technical Journal, 49: 5. May-June 1970 pp 827-852.
  https://archive.org/details/bstj49-5-827[^]

- [[[ROHM]]] ROHM Semiconductor, _Electronics Basics_,
  http://www.rohm.com/web/global/en_index[^]

- [[[vishay-e-series]]] Vishay,
  _Standard Series Values in a Decade for Resistances and Capacitances_,
  https://www.vishay.com/docs/28372/e-series.pdf[^]

// vim: tw=0
