= hw02
:stem: stem

ifeval::["{docname}" != "guidebook"]
include::subs.adoc[]
endif::[]
 

Due Wednesday 2018-01-24 at the start of class.


== Reading
Read <<AoE>> from section 2.2.6 through the end of section 2.2 (page 90).
Sections 2.2.7 through the end is the topic for Wednesday class.

Read <<AoE>> section 2.3.7, paying attenting to Figure 2.60.
The "`(figure out why)`" at the end of page 101 is the goal of the <<lab1b.adoc#,Lab 1-B Current Mirror>> circuit.

Read <<L-AoE>> chapter *4N*.



== Complete the lab circuits
For each of the Lab 1 versions:

<<lab1a.adoc#,Lab 1-A Emitter Follower>>:

* [ ] Find the values of the checkboxed items.


<<lab1b.adoc#,Lab 1-B Current Mirror>>:

* [ ] Find the values of the checkboxed items.


== AoE - Exercise 2.8 (p. 84)
****
Design an emitter follower with &pm;15 V supplies to operate over the audio range (20 Hz to 20 kHz).
Use 5 mA quiescent current and capacitive input coupling.
****

This problem uses results from <<lab1a.adoc#_amplifier,Lab 1-A Emitter Follower: &sect;2.2 Amplifier>>.

Additional question::
What is the maximum load (minimum R~load~) that can be used with this amplifier to maintain an output signal swing of at least 16 V peak-to-peak?



== Current mirror compliance
What is the output compliance of the current mirror measured in <<lab1b.adoc#_current_mirror_operation,Lab 1-B Current Mirror: &sect;2.1 Current mirror operation>>?

The term _compliance_ is defined in <<AoE>> &sect;2.2.6.D (p. 86).



//== AoE - Exercise 2.24 (p. 125)
//See <<AoE>> section 2.2.6.D for a definition of _compliance_.



ifeval::["{docname}" != "guidebook"]
include::refs.adoc[]
endif::[]

// vim: tw=0
